<?php

namespace App\Support\Errors;

/**
 * Every error a person can run into, with what happened, why, and what to do
 * about it, separately for the host (who can fix Spotify and the room) and a
 * guest (who mostly can't, and should tell the host). The short message stays
 * where the error happens; this is the "More info" behind it and the content of
 * the /help page. Codes are stable so someone can quote one.
 *
 * @phpstan-type Entry array{code: string, group: string, title: string, what: string, why: string, host: array<int, string>, guest: array<int, string>}
 */
final class ErrorCatalog
{
    public const GROUPS = [
        'JOIN' => 'Joining a room',
        'QR' => 'Scanning a QR code',
        'ROOM' => 'In the room',
        'LOC' => 'Location',
        'SP' => 'Spotify and playback',
        'AUTH' => 'Logging in',
        'HTTP' => 'Page errors',
        'NET' => 'Connection',
    ];

    /** @return array<string, Entry> */
    public static function all(): array
    {
        $callback = route('spotify.callback');

        $entries = [
            ['SP-ASLEEP', 'Your playback device is asleep or closed',
                "Spotify couldn't reach the device this room plays on.",
                'Phones, iPhones especially, put the Spotify app to sleep soon after playback pauses. A device that sleeps disappears from Spotify, and commands sent to it fail (Spotify answers "Bad gateway" or "no active device"). AuxRoom cannot wake it.',
                ['Open the Spotify app on the playback device and bring it to the front.', 'Press play in Spotify for a moment, or pick the device again in Room Settings.', 'Come back here. The room notices within a few seconds and Play works again.', 'For a device that has to stay available, use a laptop, a speaker or an Android phone as the player. On an iPhone, turn on Background App Refresh for Spotify and turn off Low Power Mode.'],
                ['Ask the host to open Spotify on the playback device.']],
            ['SP-PREMIUM', 'Spotify Premium is required',
                "Spotify won't let this account be controlled by an app.",
                'Controlling playback from outside the Spotify app is a Premium feature. A free account can listen but cannot be remote-controlled.',
                ['Use a Premium Spotify account as the host. In Room Settings, reconnect Spotify with a Premium account.', 'If the account is Premium, check that the subscription is active in your Spotify account settings.'],
                ['Let the host know. This one is theirs to fix, and the host steps explain how.']],
            ['SP-CMD', 'Spotify refused the command',
                "A play, pause, skip or similar command didn't go through.",
                'Usually a short-lived Spotify problem: the service is busy or rate limiting, the device is switching, or the device you chose is no longer the active one.',
                ['Wait a few seconds and try again.', 'Open Spotify on the playback device and make sure it is the one shown in Room Settings.', 'Pick the device again in Room Settings (Host Hub).', 'If it keeps failing, reconnect Spotify in Room Settings.'],
                ['Wait a moment and try again. If it keeps happening, tell the host.']],
            ['SP-VOLUME', "This device's volume can't be changed",
                "The device reports that it doesn't accept volume changes from outside.",
                'Many phones and some speakers control their own volume and ignore Spotify volume commands.',
                ['Use the volume buttons on the device itself.', 'To control volume from here, use a laptop or a speaker that supports Spotify Connect volume.'],
                ['Use the buttons on the playback device, or ask the host.']],
            ['SP-TRACK-GONE', "That track isn't coming up any more",
                'The track you tapped is no longer in the list.',
                'The queue changed (the song played, was skipped or the playlist moved on) between you looking at it and tapping.',
                ['Look at the refreshed list and tap again.'],
                ['Look at the refreshed list and tap again.']],
            ['SP-NO-CONTEXT', "That track can't be jumped to",
                "It isn't part of a playlist or album Spotify is playing.",
                'Jumping to a track only works inside the playlist or album that is playing. Songs added to the queue, or something playing on its own, have nowhere to jump within.',
                ['Start a playlist from the Playlist card first, then tap a track in its list.'],
                ['Ask the host to start a playlist.']],
            ['SP-DISCONNECTED', 'Spotify needs to be reconnected',
                "AuxRoom's access to the host's Spotify stopped working.",
                'Spotify turned the saved login down. That happens when access was removed in Spotify account settings, the password changed, or the Spotify app credentials were rotated or deleted.',
                ['Open Room Settings and use Reconnect Spotify, then sign in and allow access.', 'If that fails, check the client ID and secret of your Spotify app on developer.spotify.com.'],
                ['Let the host know. Reconnecting Spotify is theirs to do, and it only takes a minute.']],
            ['SP-CONNECT-CANCELLED', 'Spotify connection was cancelled',
                "You didn't finish connecting Spotify.",
                'You pressed Cancel on the Spotify page, or Spotify declined to continue.',
                ['Press Connect Spotify again and choose Agree on the Spotify page.'],
                ['Connecting Spotify is up to the host. Let them know if this keeps appearing.']],
            ['SP-CONNECT-STATE', "The Spotify connection couldn't be verified",
                'Spotify sent you back, but the check that protects the sign-in failed.',
                'The sign-in took too long, was opened in two tabs, or the session was reset in between.',
                ['Press Connect Spotify again and finish within a minute, in the same tab.'],
                ['Connecting Spotify is up to the host. Let them know if this keeps appearing.']],
            ['SP-CONNECT-CREDS', 'Add your Spotify app credentials first',
                'No client ID and secret are saved for this account.',
                'The sign-in came back before any credentials existed, usually after an earlier attempt was interrupted.',
                ['Enter the client ID and client secret of your Spotify app, then press Connect Spotify.'],
                ['Connecting Spotify is up to the host. Let them know if this keeps appearing.']],
            ['SP-CONNECT-REJECTED', 'Spotify rejected the connection',
                'Spotify answered the sign-in with an error.',
                'The most common causes: the client secret is wrong, the redirect URI is not registered in your Spotify app, or this Spotify account is not allowed to use the app yet.',
                ['Check the client ID and secret match your app on developer.spotify.com.', "In your Spotify app settings, add this exact redirect URI: {$callback}", "If you sign in with a different Spotify account than the app owner's, add that account under User Management in the app (Development Mode apps only allow a few listed users).", 'Then press Connect Spotify again.'],
                ['Connecting Spotify is up to the host. Let them know if this keeps appearing.']],
            ['ROOM-WAITING', 'Waiting for the host to let you in',
                "The host hasn't approved you yet.",
                'This room is private. The host approves each guest before they can add songs or use the controls.',
                ['This normally shows to guests who are waiting for approval. Hosts are let in automatically, so if you see it, reload the page.', 'If it keeps showing, close the room and open a new one from the home page.'],
                ['Wait for the host to approve you. They see a request in the Guests tab.']],
            ['ROOM-QUEUE-LOCKED', 'The queue is locked',
                'The host has stopped everyone from adding songs.',
                'Emergency stop is on, or queue additions were turned off for guests.',
                ['Turn Emergency stop off on the Now Playing tab to let guests add songs again.'],
                ['Ask the host to unlock the queue.']],
            ['ROOM-NO-PERMISSION', "The host hasn't given you this permission",
                "You can't do this in this room.",
                'The host chooses, per guest, who can play and pause, skip, seek, change volume, add songs and manage playlists.',
                ['Open the Guests tab and change that guest\'s permissions.'],
                ['Ask the host to allow it for you.']],
            ['ROOM-VERIFY-LOCATION', 'Verify that you are near the room',
                'This room only lets people nearby control playback.',
                "The host turned on location checking, and your location hasn't been confirmed yet.",
                ['Hosts are never asked to verify, so this normally shows to guests only.', 'To change who is checked, or how far away they can be, open the location settings in Room Settings.'],
                ['Tap "Verify my location" and allow location access. If your browser blocked it, allow location for this site in the browser settings and try again.']],
            ['ROOM-TOO-FAR', "You're too far from the room",
                'Your location is outside the area the host set.',
                'The host limited control to a radius around the room.',
                ['Widen the radius or turn location checking off in Room Settings.'],
                ['Move closer to the room and verify your location again.']],

            ['JOIN-CODE', "That invite code doesn't match an open room",
                'The code you entered is not for a room that is open right now.',
                'The code has a typo, the room was closed by its host, or the code is from an old room. Codes never contain the letters O, I or L or the digits 0 and 1, so those are always a misread.',
                ['Share the invite link or QR code with your guests. Both are in Room Settings.', 'If a guest reports this error, check they typed the whole code and that your room is still open.'],
                ['Ask the host for the current code or link, or scan the QR code on their screen.', 'Check the code carefully. It is 18 characters in three groups of six.', 'If the room was closed, the host needs to open a new one and share the new code.']],
            ['QR-DENIED', 'Camera access is blocked',
                'The browser was told not to let this site use the camera.',
                'You pressed Block on the camera prompt, or camera access for this site (or for the browser) is off in the phone settings.',
                ['Allow the camera for this site in the browser or phone settings, then press Try again.', 'Or type the invite code instead.'],
                ['On iPhone: Settings, then Safari (or the app), then Camera, then allow the site. On Android: tap the lock icon in the address bar, then Permissions, then Camera.', 'Or type the invite code instead.']],
            ['QR-UNAVAILABLE', 'No usable camera was found',
                "The device didn't offer a camera the page can use.",
                'The device has no camera, another app is using it, or the browser has no camera support (some in-app browsers).',
                ['Type the invite code instead, or open the page in the phone\'s main browser.'],
                ['Close other apps that use the camera, or open the page in Safari or Chrome. You can always type the invite code instead.']],
            ['QR-NOPICTURE', "The camera opened but shows no picture",
                'The camera started but did not deliver any image.',
                'Usually a browser glitch, especially right after switching apps or granting access. Some phones need a second try.',
                ['Press Try again. If it still shows nothing, close and reopen the page, or type the code.'],
                ['Press Try again. If it still shows nothing, close and reopen the page, or type the invite code.']],
            ['QR-ERROR', "The camera couldn't be started",
                'Something went wrong while opening the camera.',
                'The camera was busy, access was interrupted, or the browser refused for another reason.',
                ['Press Try again, or type the invite code.'],
                ['Press Try again, or type the invite code.']],
            ['LOC-UNSUPPORTED', 'This browser cannot share its location',
                "The browser doesn't support location.",
                'Very old browsers, and some in-app browsers, have no location support.',
                ['Open AuxRoom in Safari or Chrome. Or enter the coordinates by hand.'],
                ['Open AuxRoom in Safari or Chrome to verify your location.']],
            ['LOC-FAILED', "Your location couldn't be found",
                "The browser couldn't work out where you are.",
                'Location is switched off, access was blocked for this site, or the device has no GPS or network signal right now (for example indoors with location services off).',
                ['Allow location for this site, turn on location services, and try again. Or drop the pin on the map by hand.'],
                ['Allow location for this site, turn on location services on the phone, and try again.']],
            ['LOC-INVALID', 'Those coordinates are not valid',
                'Latitude must be between -90 and 90, and longitude between -180 and 180.',
                'A number was typed outside those ranges, or the fields mix up latitude and longitude.',
                ['Enter latitude first (for example 52.37), then longitude (for example 4.90).'],
                ['That setting belongs to the host, so let them know.']],
            ['LOC-UNSET', 'Set a location first',
                'Location checking needs a place to measure from.',
                'It is switched on, but no centre point has been chosen.',
                ['Use "Use my location", drop the pin on the map, or enter coordinates, then save.'],
                ['That setting belongs to the host, so let them know.']],
            ['AUTH-FAILED', "Those login details don't match",
                "The email or password isn't right.",
                'A typo, the wrong account, or a password that was changed. Guests do not need an account to join a room; only hosts log in.',
                ['Check the email and password, or use "Forgot your password?" to reset it.'],
                ['You do not need an account to join a room. Use the invite code or link.']],
            ['AUTH-THROTTLE', 'Too many login attempts',
                'Logging in is paused for a short time.',
                'Several wrong attempts in a row. The pause protects the account from guessing.',
                ['Wait for the time shown, then try again, or reset the password.'],
                ['You do not need an account to join a room. Use the invite code or link.']],
            ['HTTP-401', 'Sign in required',
                'This page needs you to be logged in.',
                'You opened a host page while logged out, or your login expired.',
                ['Log in again. Sign in from the home page.'],
                ['Guests do not log in. Use the invite link or code to join a room.']],
            ['HTTP-403', 'Access denied',
                "You aren't allowed to do this.",
                'The action belongs to someone else, for example closing a room you do not host.',
                ['Check that you are logged in as the account that created the room.'],
                ['This is something only the host can do. If you need it, ask them.']],
            ['HTTP-404', 'Page not found',
                "That page doesn't exist, or the room is closed.",
                'The link has a typo, or the room it points to was closed. Closed rooms vanish completely, including their party screen.',
                ['Open a new room from the home page if yours was closed.'],
                ['Ask the host for a fresh invite link or code.']],
            ['HTTP-405', 'That action is not supported here',
                'The page does not accept that kind of request.',
                'A stale page, a bookmark to an action rather than a page, or a browser extension altering the request.',
                ['Go back to the home page and open the page again.'],
                ['Go back to the home page and try again.']],
            ['HTTP-419', 'Page expired',
                'Your session timed out for security.',
                'The page stayed open long enough for its security token to expire. This is common when the installed app was left in the background.',
                ['Reload the page and repeat what you were doing. Nothing was lost.'],
                ['Reload the page and repeat what you were doing.']],
            ['HTTP-429', 'Too many requests',
                'You did something too many times too quickly.',
                'Joining, logging in and loading pictures are rate limited. Several people on one network can trip it together.',
                ['Wait a minute and try again.'],
                ['Wait a minute and try again.']],
            ['HTTP-500', 'Something went wrong on our side',
                'An unexpected error happened on the server.',
                'A bug or a service the app depends on had a problem. It is logged with the reference ID shown on the page.',
                ['Try again in a moment. If it repeats, send the reference ID from the error page to whoever runs AuxRoom.'],
                ['Try again in a moment. If it repeats, tell the host and include the reference ID.']],
            ['HTTP-503', 'AuxRoom is briefly unavailable',
                'The service is paused for maintenance or an update.',
                'An update is being installed. It normally takes under a minute.',
                ['Wait a minute and reload.'],
                ['Wait a minute and reload.']],
            ['NET-OFFLINE', "You're offline",
                "The device lost its internet connection.",
                'Wi-Fi or mobile data dropped. AuxRoom needs a connection to sync the room, and returns by itself when it is back.',
                ['Check Wi-Fi or mobile data. Playback on the speaker is not interrupted by this.'],
                ['Check Wi-Fi or mobile data. The room stays as it is and you rejoin automatically.']],
        ];

        $all = [];

        foreach ($entries as [$code, $title, $what, $why, $host, $guest]) {
            $all[$code] = [
                'code' => $code, 'group' => strstr($code, '-', true), 'title' => $title,
                'what' => $what, 'why' => $why, 'host' => $host, 'guest' => $guest,
            ];
        }

        return $all;
    }

    /** @return Entry|null */
    public static function find(?string $code): ?array
    {
        return $code ? (self::all()[$code] ?? null) : null;
    }
}
